In [1]:
import json
import pandas as pd

In [3]:
with open('data/yelp_academic_dataset_business.json') as data_file:
    data = [json.loads(row) for row in data_file ]
    #business_data = pd.DataFrame(data)

In [12]:
#there are business then dont have all days on 'hours'
business_no_sunday = [ row['business_id'] for row in data if row['hours'] is not None and 'Sunday' not in row['hours'] ]
display(len(business_no_sunday))
business_no_sunday[:4]

62433

['6OAZjbxqM5ol29BuHsil3w',
 '51M2Kk903DFYI6gnB5I6SQ',
 'cKyLV5oWZJ2NudWgqs8VZw',
 'oiAlXZPIFm2nBCt0DHLu_Q']

In [6]:
with open('data/yelp_academic_dataset_review.json') as data_file:
    review = (json.loads(row) for row in data_file ) #the file is to big so we use a iterators
    review_cool = (row for row in review if row['cool'] != 0)
    display(review_cool.__next__())

{'review_id': 'z4BCgTkfNtCu4XY5Lp97ww',
 'user_id': 'jOERvhmK6_lo_XGUBPws_w',
 'business_id': 'Ws8V970-mQt2X9CwCuT5zw',
 'stars': 4.0,
 'useful': 3,
 'funny': 0,
 'cool': 1,
 'text': 'I have been here twice. Very nice and laid back. I tried the weekend Southern menu and it was delicious! Collard greens, mac&cheese, ribs, BBQ chicken sandwich. The scone with clotted cream was divine!!!! The iced teas are very refreshing and I swear I drank a whole container myself both visits. \nThe second time I had soup, salad and a sandwich. The salad had this amazing (raspberry? strawberry?, I forgot) vinaigrette. The sandwich was good, but I was kind of disappointed with the soup. It was potato and tasted too "milky". \nThey change the menu often and now have a tea inspired one. Can\'t wait to go back and try it.\nThe owners are very nice and I hope they continue to do well.',
 'date': '2009-10-13 04:16:41'}

In [12]:
cool_values = dict()
with open('data/yelp_academic_dataset_review.json') as data_file:
    review = (json.loads(row) for row in data_file ) #the file is to big so we use a iterators
    for row in review:
        cool_score = row['cool']
        if cool_score in cool_values:
            cool_values[cool_score] = 1 + cool_values[cool_score]
        else:
            cool_values[cool_score] = 1
for i in range(-1, 503):
    print(f'score: {i}, count {cool_values[i]}')

{0: 6056599,
 1: 1206763,
 20: 1432,
 4: 74602,
 2: 360161,
 10: 8370,
 6: 28930,
 3: 146391,
 12: 5261,
 5: 44281,
 8: 14541,
 11: 6695,
 7: 20297,
 13: 4371,
 93: 25,
 9: 10923,
 19: 1621,
 31: 440,
 17: 2182,
 47: 167,
 16: 2465,
 22: 1193,
 28: 598,
 14: 3456,
 15: 2987,
 40: 268,
 21: 1261,
 25: 858,
 43: 230,
 26: 842,
 23: 1006,
 27: 671,
 24: 924,
 18: 1941,
 33: 386,
 32: 422,
 55: 119,
 51: 126,
 57: 111,
 41: 237,
 46: 159,
 37: 290,
 34: 431,
 38: 300,
 54: 118,
 39: 258,
 49: 158,
 89: 36,
 50: 152,
 30: 498,
 29: 553,
 36: 309,
 53: 119,
 35: 348,
 85: 34,
 67: 65,
 42: 214,
 72: 46,
 84: 22,
 69: 46,
 48: 158,
 91: 26,
 82: 27,
 66: 78,
 71: 27,
 99: 24,
 60: 109,
 44: 189,
 92: 20,
 97: 13,
 77: 33,
 75: 34,
 78: 37,
 114: 11,
 52: 153,
 62: 66,
 63: 79,
 80: 40,
 56: 114,
 74: 52,
 110: 13,
 112: 16,
 58: 88,
 45: 189,
 79: 31,
 111: 11,
 98: 24,
 65: 53,
 64: 63,
 88: 24,
 109: 17,
 156: 5,
 104: 15,
 118: 9,
 134: 4,
 86: 26,
 122: 10,
 68: 56,
 127: 9,
 115: 10,
 130: 12,
 90: 15,
 59: 101,
 94: 14,
 157: 1,
 95: 16,
 70: 53,
 87: 28,
 73: 44,
 76: 42,
 61: 105,
 185: 1,
 125: 7,
 117: 10,
 119: 9,
 188: 1,
 81: 25,
 101: 24,
 178: 2,
 183: 1,
 147: 4,
 158: 5,
 100: 11,
 199: 1,
 137: 4,
 120: 5,
 105: 13,
 142: 5,
 83: 28,
 126: 4,
 197: 2,
 108: 11,
 96: 17,
 174: 2,
 121: 7,
 128: 8,
 107: 10,
 194: 3,
 193: 3,
 143: 5,
 202: 2,
 133: 7,
 116: 5,
 103: 15,
 187: 3,
 141: 7,
 102: 14,
 144: 5,
 189: 1,
 205: 2,
 138: 8,
 106: 19,
 131: 8,
 132: 4,
 124: 6,
 325: 1,
 151: 3,
 113: 5,
 136: 5,
 129: 6,
 195: 1,
 123: 7,
 162: 2,
 198: 1,
 180: 1,
 177: 1,
 211: 1,
 139: 4,
 196: 3,
 140: 3,
 135: 5,
 181: 1,
 191: 1,
 171: 1,
 172: 1,
 153: 4,
 190: 2,
 148: 2,
 145: 3,
 222: 1,
 173: 1,
 149: 1,
 203: 1,
 166: 1,
 284: 1,
 165: 1,
 390: 1,
 182: 1,
 163: 1,
 175: 1,
 502: 1,
 160: 1,
 212: 1,
 -1: 1,
 169: 1,
 164: 1,
 310: 1,
 167: 1,
 179: 1,
 321: 1}

score: -1, count 1
score: 0, count 6056599
score: 1, count 1206763
score: 2, count 360161
score: 3, count 146391
score: 4, count 74602
score: 5, count 44281
score: 6, count 28930
score: 7, count 20297
score: 8, count 14541
score: 9, count 10923
score: 10, count 8370
score: 11, count 6695
score: 12, count 5261
score: 13, count 4371
score: 14, count 3456
score: 15, count 2987
score: 16, count 2465
score: 17, count 2182
score: 18, count 1941
score: 19, count 1621
score: 20, count 1432
score: 21, count 1261
score: 22, count 1193
score: 23, count 1006
score: 24, count 924
score: 25, count 858
score: 26, count 842
score: 27, count 671
score: 28, count 598
score: 29, count 553
score: 30, count 498
score: 31, count 440
score: 32, count 422
score: 33, count 386
score: 34, count 431
score: 35, count 348
score: 36, count 309
score: 37, count 290
score: 38, count 300
score: 39, count 258
score: 40, count 268
score: 41, count 237
score: 42, count 214
score: 43, count 230
score: 44, count 189
score: 45, count 189
score: 46, count 159
score: 47, count 167
score: 48, count 158
score: 49, count 158
score: 50, count 152
score: 51, count 126
score: 52, count 153
score: 53, count 119
score: 54, count 118
score: 55, count 119
score: 56, count 114
score: 57, count 111
score: 58, count 88
score: 59, count 101
score: 60, count 109
score: 61, count 105
score: 62, count 66
score: 63, count 79
score: 64, count 63
score: 65, count 53
score: 66, count 78
score: 67, count 65
score: 68, count 56
score: 69, count 46
score: 70, count 53
score: 71, count 27
score: 72, count 46
score: 73, count 44
score: 74, count 52
score: 75, count 34
score: 76, count 42
score: 77, count 33
score: 78, count 37
score: 79, count 31
score: 80, count 40
score: 81, count 25
score: 82, count 27
score: 83, count 28
score: 84, count 22
score: 85, count 34
score: 86, count 26
score: 87, count 28
score: 88, count 24
score: 89, count 36
score: 90, count 15
score: 91, count 26
score: 92, count 20
score: 93, count 25
score: 94, count 14
score: 95, count 16
score: 96, count 17
score: 97, count 13
score: 98, count 24
score: 99, count 24
score: 100, count 11
score: 101, count 24
score: 102, count 14
score: 103, count 15
score: 104, count 15
score: 105, count 13
score: 106, count 19
score: 107, count 10
score: 108, count 11
score: 109, count 17
score: 110, count 13
score: 111, count 11
score: 112, count 16
score: 113, count 5
score: 114, count 11
score: 115, count 10
score: 116, count 5
score: 117, count 10
score: 118, count 9
score: 119, count 9
score: 120, count 5
score: 121, count 7
score: 122, count 10
score: 123, count 7
score: 124, count 6
score: 125, count 7
score: 126, count 4
score: 127, count 9
score: 128, count 8
score: 129, count 6
score: 130, count 12
score: 131, count 8
score: 132, count 4
score: 133, count 7
score: 134, count 4
score: 135, count 5
score: 136, count 5
score: 137, count 4
score: 138, count 8
score: 139, count 4
score: 140, count 3
score: 141, count 7
score: 142, count 5
score: 143, count 5
score: 144, count 5
score: 145, count 3

KeyError: 146